name: Chromatic test

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/components/**"

env:
  node-version: lts/*
  TZ: Asia/Tokyo

jobs:
  run-chromatic-test:
    runs-on: ubuntu-latest
    needs: front-filter
    defaults:
      run:
        working-directory: ${{ env.workdir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Build Storybook
        run: yarn run build-storybook
