name: chromatic

on:
  workflow_run:
    workflows:
      - Chromatic test
    types:
      - completed

env:
  node-version: lts/*

jobs:
  run-chromatic-deployment:
    name: Deploy Storybook to chromatic
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
